export const validation = {
    F_NAME: {
        slug: "f_name",
        type: "text",
        pattern: /^[a-zA-Z]{3,}(\s)?([a-zA-Z]+)?$/,
        title: "Please enter First Name",
        error: "Invalid First Name",
        required: true,
        id: "firstName",
        autoCapitalize: "characters",
    },
    M_NAME: {
        slug: 'm_name',
        type: "text",
        pattern: /^[a-zA-Z]{3,}(\s)?([a-zA-Z]+)?$/,
        title: "Please enter Middle Name",
        error: "Invalid Middle Name",
        required: false,
        id: "middleName",
        autoCapitalize: "characters",
    },
    L_NAME: {
        slug: 'l_name',
        type: "text",
        pattern: /^[a-zA-Z]{3,}(\s)?([a-zA-Z]+)?$/,
        title: "Please enter Last Name",
        error: "Invalid Last Name",
        required: true,
        id: "lastName",
        autoCapitalize: "characters",
    },
    MOBILE: {
        slug: 'mobile',
        type: "number",
        pattern: /^[0-9]{10}$/,
        title: "Please enter Mobile Number",
        error: "Invalid Mobile Number",
        required: true,
        id: "numberMobile",
    },
    EMAIL: {
        slug: 'email',
        type: "text",
        pattern: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
        title: "Please enter Email",
        error: "Invalid Email",
        required: true,
        id: "textEmail",
        autoCapitalize: "characters"
    },
    GENDER: {
        slug: 'gender',
        type: "button",
        required: true,
        id: 'genderHuman',
        pattern: /^[a-z]$/,
    },
    OWNERSHIP: {
        slug: 'ownership',
        type: "button",
        required: true,
        id: 'residenceOwnership',
        pattern: /^[a-z]+$/
    },
    ADDRESS1: {
        slug: 'address1',
        type: "text",
        required: true,
        pattern: /^[^]+$/,
        id: "textAddress1",
        title: "Please enter Address 1",
        error: "Invalid Address 1",
        autoCapitalize: "characters",
    },
    ADDRESS2: {
        slug: 'address2',
        type: "text",
        required: false,
        pattern: /^[^]+$/,
        id: "textAddress2",
        title: "Please enter Address 2",
        error: "Invalid Address 2",
        autoCapitalize: "characters",
    },
    DOB: {
        slug: 'dob',
        id: 'dobDate',
        required: true,
        dateFormat: "dd/MM/yyyy",
        pattern: /^[0-9]{2}\/[0-9]{2}\/[0-9]{4}$/,
    },
    PINCODE: {
        slug: 'pincode',
        type: "number",
        title: "Please enter Pincode",
        required: true,
        id: "numberPincode",
        pattern: /^[0-9]{6}$/,
        autoCapitalize: "characters"
    },
}