steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:${_VERSION}', '-f', './ci/Dockerfile', '.']

# my-image is pushed to Container Registry
images:
- 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'
