apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: _APP_NAME_-_CI_ENVIRONMENT_SLUG_-deployment
spec:
  replicas: _REPLICAS_
  selector:
    matchLabels:
      app: _APP_NAME_-_CI_ENVIRONMENT_SLUG_
  # Pod template
  template:
    metadata:
      labels:
        app: _APP_NAME_-_CI_ENVIRONMENT_SLUG_
        track: _TRACK_
    spec:
      containers:
        - name: app
          image: gcr.io/_PROJECT_NAME_/_APP_NAME_:_VERSION_
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          - name: DBHOST
            value: "mintifi.cjrmgd0cxy3y.us-east-1.rds.amazonaws.com"
          - name: DBNAME 
            value: "mintifi_qa"
          - name: DBPASS
            value: "mq`x4hD]{>~T5dQs"
          - name: MONGODBNAME 
            value: "mintifi"
          - name: MONGOHOST 
            value: "35.200.135.189"
          - name: MONGOPORT
            value: "27017"
          - name: REDISHOST
            value: "13.233.63.70"
          - name: REDISPORT
            value: "6379"
          - name: DEFAULTURL
            value: "new-qa.mintifi.com"
          - name: S3REGION
            value: "ap-south-1"
          - name: S3HOSTNAME
            value: "s3-ap-south-1.amazonaws.com"
          - name: S3BUCKETNAME 
            value: "mintifi-qa"
          - name: EMAILPREFIX
            value: "MINTIFI-QA" 
